from typing import Optional, Protocol
from requests import Response
from SRC.main.api.models.base_modul import BaseModel


class CredEndpoint(Protocol):
    def post(self, model:Optional[BaseModel])-> BaseModel | Response:...
    def get(self, user_id: int)-> BaseModel | Response:...
    def delete(self, user_id:int) -> BaseModel | Response:...
